# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12cb9c291d7258d9570888f48b059038"
name = "observa dev"
handle = "observa-dev"
application_url = "https://nominated-katie-ethnic-allowing.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_orders,write_products, write_pixels, read_pixels, read_customers, read_checkouts, read_customer_events"

[auth]
redirect_urls = ["https://nominated-katie-ethnic-allowing.trycloudflare.com/auth/callback", "https://nominated-katie-ethnic-allowing.trycloudflare.com/auth/shopify/callback", "https://nominated-katie-ethnic-allowing.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
