# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12cb9c291d7258d9570888f48b059038"
name = "observa dev"
handle = "observa-dev"
application_url = "https://eating-maria-express-expect.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_products"

[auth]
redirect_urls = ["https://eating-maria-express-expect.trycloudflare.com/auth/callback", "https://eating-maria-express-expect.trycloudflare.com/auth/shopify/callback", "https://eating-maria-express-expect.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
