# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "12cb9c291d7258d9570888f48b059038"
name = "observa dev"
handle = "observa-dev"
application_url = "https://onion-israeli-smell-kinds.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customer_events,read_customers,read_orders,read_pixels,write_orders,write_pixels,write_products"

[auth]
redirect_urls = ["https://onion-israeli-smell-kinds.trycloudflare.com/auth/callback", "https://onion-israeli-smell-kinds.trycloudflare.com/auth/shopify/callback", "https://onion-israeli-smell-kinds.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
