# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "feaaffcbe235d0c4ea027da7deae933e"
name = "observa-dev-app"
handle = "observa-dev-app"
application_url = "https://rw-smithsonian-chess-iowa.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_customer_events,read_customers,read_orders,read_pixels,write_orders,write_pixels,write_products"

[auth]
redirect_urls = [
  "https://rw-smithsonian-chess-iowa.trycloudflare.com/auth/callback",
  "https://rw-smithsonian-chess-iowa.trycloudflare.com/auth/shopify/callback",
  "https://rw-smithsonian-chess-iowa.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
