# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30eb04ccb90771617547fd6f6ea5e70d"
name = "observa"
handle = "observa"
application_url = "https://observa-two.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_products, write_pixels, read_pixels, read_customer_events"

[auth]
redirect_urls = [
  "https://observa-two.vercel.app/auth/callback",
  "https://observa-two.vercel.app/auth/shopify/callback",
  "https://observa-two.vercel.app/api/auth/callback"
]

[pos]
embedded = false
