# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30eb04ccb90771617547fd6f6ea5e70d"
name = "observa"
handle = "observa"
application_url = "https://reproductive-toolbox-walt-better.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_products"

[auth]
redirect_urls = ["https://reproductive-toolbox-walt-better.trycloudflare.com/auth/callback", "https://reproductive-toolbox-walt-better.trycloudflare.com/auth/shopify/callback", "https://reproductive-toolbox-walt-better.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
