# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "30eb04ccb90771617547fd6f6ea5e70d"
name = "observa"
handle = "observa"
application_url = "https://celebrities-za-crafts-european.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "https://ai-speed-booster-app.fly.dev/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://ai-speed-booster-app.fly.dev/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://ai-speed-booster-app.fly.dev/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_products, write_pixels, read_pixels, read_customer_events"

[auth]
redirect_urls = [
  "https://celebrities-za-crafts-european.trycloudflare.com/auth/callback",
  "https://celebrities-za-crafts-european.trycloudflare.com/auth/shopify/callback",
  "https://celebrities-za-crafts-european.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
