# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "22a9021f969e67bbec290063185dc852"
name = "Performance Monitor"
handle = "performance-monitor-1"
application_url = "https://readily-accused-consultation-consistency.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://readily-accused-consultation-consistency.trycloudflare.com/auth/callback",
  "https://readily-accused-consultation-consistency.trycloudflare.com/auth/shopify/callback",
  "https://readily-accused-consultation-consistency.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
