/**
 * Generated by Dezi v0.3.0
 * Generated on: 2025-09-11T07:12:36.744Z
 *
 * This code uses Shopify Polaris components which are subject to the MIT license:
 * Copyright (c) 2017-present Shopify Inc.
 * https://github.com/Shopify/polaris
 */

import { Badge, Card, Page } from "@shopify/polaris";
import { json } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
import prisma from "../db.server";
import { authenticate } from "../shopify.server";
import { SetupGuideExample } from "../components/SetupGuide.jsx";

export const loader = async ({ request }) => {
  const { session } = await authenticate.admin(request);
  const shop = session.shop;
  const shopSlug = shop?.replace?.(".myshopify.com", "") || shop;

  let settings = await prisma.alertSettings.findUnique({ where: { shop } });
  if (!settings) {
    settings = await prisma.alertSettings.create({ data: { shop } });
  }

  return json({ settings, shop, shopSlug });
};

export default function GuideSetupPage() {
  const { settings, shopSlug } = useLoaderData();
  return (
    <Page title="Setup Guide" titleMetadata={<Badge>Guide</Badge>}>
      <Card padding="0" />
      <SetupGuideExample settings={settings} shopSlug={shopSlug} />
    </Page>
  );
}